language: shell
dist: trusty
sudo: required

services:
  - docker

before_script:
    - cd docker
    - docker network create OMS
    - docker-compose up -d
    - docker-compose logs
    - sleep 120
    - sudo docker-compose logs


script:
    - sudo docker-compose run -T omscore ./vendor/bin/phpunit
