version: '3.3'

services:

### OMS CORE        #######################################
### Workspace Utilities Container ###########################

    omscore:
        build:
          context: ./$PATH_OMS_CORE/omscore/
          dockerfile: ./Dockerfile.dev
        image: aegee/omscore:dev
        volumes:
            - type: bind
              source: ./$PATH_OMS_CORE/../
              target: /var/www
            - type: volume
              source: shared
              target: /var/shared



### PHP-FPM Container #######################################

    php-fpm:
        build:
          context: ./$PATH_OMS_CORE/php-fpm/
          dockerfile: ./Dockerfile.dev
        image: aegee/php-fpm:dev
        volumes:
            - type: bind
              source: ./$PATH_OMS_CORE/../
              target: /var/www
        expose:
            - "9000"

### Nginx Server Container ##################################

    omscore-nginx:
        build:
          context: ./$PATH_OMS_CORE/omscore-nginx/
          dockerfile: ./Dockerfile.dev
        image: aegee/omscore-nginx:dev
        volumes:
            - type: bind
              source: ./$PATH_OMS_CORE/../
              target: /var/www
        links:
            - php-fpm
        expose:
            - "80"
        labels:
            - "traefik.backend=omscore"
            - "traefik.port=80"
            - "traefik.frontend.rule=HostRegexp:{domain:[a-z0-9.]+}"
            - "traefik.frontend.priority=10"
            - "traefik.enable=true"
            - "registry.categories=(users, 10);(antennae, 10);(notifications, 0)"
            - "registry.backend=/api"
            - "registry.description=The core module with both backend and frontend"

### PostgreSQL Container ####################################

    postgres:
        image: postgres:latest
        volumes:
            - postgres:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_DB: homestead
            POSTGRES_USER: homestead
            POSTGRES_PASSWORD: secret

### pgAdmin Container #######################################

    pgadmin:
        image: fenglc/pgadmin4
        ports:
            - "8081:5050"
        links:
            - postgres
### Volumes Setup ###########################################

volumes:
    postgres:
        driver: "local"
    shared:
        driver: "local"

networks:
  default:
    external:
      name: OMS
