FROM php:7.1

#
#--------------------------------------------------------------------------
# OS-level Dependencies
#--------------------------------------------------------------------------

RUN DEBIAN_FRONTEND=noninteractive

#oms-core simply serves as a file system, therefore it only needs to check if it can access the files.
HEALTHCHECK --interval=30s --timeout=3s \
  CMD [ -f /var/www/app/Http/Kernel.php ]

ENV TERM xterm

RUN apt-get update
RUN apt-get install -y \
        zlib1g-dev libicu-dev g++ \
        libpq-dev \
        git \
        curl \
        nano \
        npm

RUN docker-php-ext-install intl
RUN docker-php-ext-install pdo pdo_pgsql pgsql

RUN apt-get clean



#
#--------------------------------------------------------------------------
# App-level Dependencies
#--------------------------------------------------------------------------

RUN npm install -g gulp
RUN npm cache clean --force
#TODO: remove the --force from above npm cache?
RUN ln -s /usr/bin/nodejs /usr/bin/node

# Install composer and add its bin to the PATH.
RUN curl -s http://getcomposer.org/installer | php && \
    echo "export PATH=${PATH}:/var/www/vendor/bin" >> ~/.bashrc && \
    mv composer.phar /usr/local/bin/composer

ARG PUID=1000
ARG PGID=1000
RUN groupadd -g $PGID laradock && \
    useradd -u $PUID -g laradock -m laradock

# Source the bash
RUN . ~/.bashrc



#
#--------------------------------------------------------------------------
# Bootstrap
#--------------------------------------------------------------------------

ADD ./bootstrap.sh /var/scripts/bootstrap.sh

RUN chown -R laradock:laradock /var/scripts/
RUN echo "export PS1=\"\[\e[31m\]\u\[\e[m\]@\[\e[32m\][\[\e[m\]\[\e[32m\]omscore\[\e[m\]\[\e[32m\]]\[\e[m\]\[\e[34m\]\H\[\e[m\]:\[\e[33m\]\w\[\e[m\]\\$  \"" >> ~/.bashrc

WORKDIR /var/www



CMD chown -R laradock:laradock /var/www/ \
    && sh /var/scripts/bootstrap.sh \
    && gulp watch # TODO: also run this as laradock
