FROM phusion/baseimage:latest

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

RUN DEBIAN_FRONTEND=noninteractive
RUN locale-gen en_US.UTF-8

#oms-core simply serves as a file system, therefore it only needs to check if it can access the files.
HEALTHCHECK --interval=30s --timeout=3s \
  CMD [ -f /var/www/app/Http/Kernel.php ]

ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV TERM xterm

# Add the "PHP 7" ppa
RUN apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:ondrej/php

#
#--------------------------------------------------------------------------
# Software's Installation
#--------------------------------------------------------------------------
#

# Install "PHP Extentions", "libraries", "Software's"
RUN apt-get update
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-cli
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-common
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-curl
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-json
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-xml
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-mbstring
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-mcrypt
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-mysql
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-pgsql
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-sqlite
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-sqlite3
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-zip
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-bcmath
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-memcached
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-gd
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-dev
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        php7.1-intl
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        pkg-config
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        libcurl4-openssl-dev
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        libedit-dev
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        libssl-dev
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        libxml2-dev
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        xz-utils
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        libsqlite3-dev
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        sqlite3
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        git
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        curl
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        vim
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        nano
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        postgresql-client
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        nodejs
RUN apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
        npm
RUN apt-get clean
RUN npm install -g gulp
RUN npm cache clean --force
RUN ln -s /usr/bin/nodejs /usr/bin/node

#####################################
# Composer:
#####################################

# Install composer and add its bin to the PATH.
RUN curl -s http://getcomposer.org/installer | php && \
    echo "export PATH=${PATH}:/var/www/vendor/bin" >> ~/.bashrc && \
    mv composer.phar /usr/local/bin/composer

ARG PUID=1000
ARG PGID=1000
RUN groupadd -g $PGID laradock && \
    useradd -u $PUID -g laradock -m laradock

# Source the bash
RUN . ~/.bashrc


#####################################
# omscore bootstrap
#####################################

ADD ./bootstrap.sh /var/scripts/bootstrap.sh

RUN chown -R laradock:laradock /var/scripts/
RUN echo "export PS1=\"\[\e[31m\]\u\[\e[m\]@\[\e[32m\][\[\e[m\]\[\e[32m\]omscore\[\e[m\]\[\e[32m\]]\[\e[m\]\[\e[34m\]\H\[\e[m\]:\[\e[33m\]\w\[\e[m\]\\$  \"" >> ~/.bashrc

WORKDIR /var/www

# Create any file in the shared volume to overcome docker bug
CMD chown -R laradock:laradock /var/www \
    && touch /var/shared/api-key \
    && chown -R laradock:laradock /var/shared \
    && sh /var/scripts/bootstrap.sh \
    && gulp watch # TODO: also run this as laradock
